### ISSUE TITLE
Participant1 & Participant2 StructureDefinitions : @typeCode="PART" has been removed from ValueSet "CDAParticipationType"

### ISSUE THREAD

**Issue by udaychandrupatla** [HL7/CDA-core-sd#19]
participant@typeCode attribute value of "PART" has been removed from the new ValueSet  "CDAParticipationType" which was present in the old ValueSet at https://terminology.hl7.org/5.5.0/ValueSet-v3-ParticipationType.html

other such codes which were removed are -
- TRANS
- NOTARY

**Comment by benjaminflessner** [comment]
The ValueSets in this IG were created to limit values to only those allowed in RIM 2.07, the version used by the original CDA specification. See: https://jira.hl7.org/browse/CDA-20815 . The version used in CDA R2.0 did not include PART, TRANS, or NOTARY: https://www.hl7.org/cda/stds/online-navigation/2024May/infrastructure/vocabulary/ParticipationType.htm

Interestingly, it looks like we missed that in the original implementation of CDA-20815, so the recent THO-Fix terminology fixed this by accident. I will likely update the value set definition to match the others that end with ` - limited to values allowed in original CDA definition`

**Comment by udaychandrupatla** [comment]
Thanks for the change in the description in the valueSet @benjaminflessner

I was wondering if you are thinking of adding value "PART" in the "CDAParticipationType" valueSet as we have some CDA implementations which mandate "PART" as a mandatory @typeCode attribute value for ClinicalDocument\Participant.
